---
#default_locale: en
#locales: 
#  $ref: locales.yml
name: "JazzHub project toolchain"
description: "With this toolchain, you can bookmark existing tools in your [JazzHub project](https://hub.jazz.net). \n\nTo get started, click **Create**."
version: 0.1
# Generate base64 representation of image at http://www.askapache.com/online-tools/base64-image-converter/
image: data:image/png;base64,$file(jazzhub-toolchain.png,base64)
required: 
 - ccm
 - git
 - webide

ccm:
  service_id: customtool
  parameters:
    type: Track & Plan
    lifecyclePhase: "THINK"
    imageUrl: https://www.ibm.com/cloud-computing/bluemix/images/catalog-trackplan.png
    documentationUrl:
    name: "{{name}}"
    dashboard_url:
    description:
    additional-properties:
  
git:
  service_id: customtool
  parameters:
    type: Hosted Git
    lifecyclePhase: "CODE"
    imageUrl: https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png
    documentationUrl:
    name: "{{name}}"
    dashboard_url:
    description:
    additional-properties:

webide:
  service_id: customtool
  parameters:
    type: Eclipse WebIDE
    lifecyclePhase: "CODE"
    imageUrl: http://www.eclipse.org/ecd/img/eclipse256.png
    documentationUrl:
    name: "{{name}}"
    dashboard_url:
    description:
    additional-properties:
    
pipeline:
  service_id: customtool
  parameters:
    type: Delivery Pipeline
    lifecyclePhase: "DELIVER"
    imageUrl: https://www.ibm.com/cloud-computing/bluemix/images/catalog-deliverypipeline.png
    documentationUrl:
    name: "{{name}}"
    dashboard_url:
    description:
    additional-properties:
  

